# docker-compose up -d
# docker-compose logs -f
# docker-compose down (docker-compose down -v)

# 실행하려는 컨테이너 그룹
services:
  db:
    # 사용할 도커 이미지 -> postgres 15 버전
    image: postgres:15

    # 컨테이너의 이름
    container_name: lifelogix-db

    # 컨테이너 내부 환경 변수 -> PostgreSQL 컨테이너 초기 DB 설정
    environment:
      - POSTGRES_USER=lifelogix     # 데이터베이스 사용자 이름
      - POSTGRES_PASSWORD=lifelogix # 데이터베이스 비밀번호
      - POSTGRES_DB=lifelogix       # 데이터베이스 이름

    # 포트 연결 -> 내 PC(호스트)의 5432 포트로 오는 요청을 컨테이너의 5432 포트로 전달
    ports:
      - "5432:5432"

    # 데이터를 영속적으로 저장하기 위해 볼륨 연결
    volumes:
      - ./data:/var/lib/postgresql/data

  # 2. Redis 서비스
  redis:
    image: redis:alpine
    container_name: lifelogix-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data # Redis 데이터는 'redis-data'라는 이름의 볼륨에 저장

volumes:
  redis-data:
    # 'redis-data' -> Docker가 관리하는 '이름 있는 볼륨(named volume)'
    # 'db' 서비스는 './data'라는 '바인드 마운트(bind mount)'를 사용