# 모든 환경에 적용되는 공통 설정
spring:
  profiles:
    active: local
  jpa:
    # JPA 관련 공통 설정
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET}

# JWT 관련 공통 설정
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: 3600000    # 1시간
  refresh-token-expiration-ms: 604800000 # 7일