# 모든 환경에 적용되는 공통 설정
spring:
  profiles:
    active: prod # 기본 활성 프로필
  jpa:
    properties:
      hibernate:
        # PostgreSQL 방언 설정 (모든 환경 공통)
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: jcache
    jcache:
      provider: org.redisson.jcache.configuration.RedissonCachingProvider

bucket4j:
  cache-to-use: jcache # Bucket4j 캐시 매니저로 JCache 사용

# JWT 관련 공통 설정
jwt:
  secret: ${JWT_SECRET} # 환경 변수 사용
  access-token-validity-seconds: 3600    # 1시간
  refresh-token-validity-seconds: 604800 # 7일

# oauth2 관련 공통 설정 (authorized-redirect-uris는 환경별로 분리)
# 필요시 여기에 공통 OAuth2 설정 추가