spring:
  datasource:
    # 도커 컴포즈 환경 변수 참고
    url: jdbc:postgresql://localhost:5432/lifelogix
    username: lifelogix
    password: lifelogix
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          # Base64 인코딩된 비밀 키 (jwt.secret과 동일한 값)
          secret-key: 'a2VlcGl0c2VjcmV0Zm9ybGlmZWxvZ2l4cHJvamVjdGJ5dGFjdA=='

jwt:
  secret: 'a2VlcGl0c2VjcmV0Zm9ybGlmZWxvZ2l4cHJvamVjdGJ5dGFjdA==' # Base64 인코딩된 임시 비밀 키
  expiration-ms: 3600000 # 1시간 (밀리초 단위)