# 모든 환경에 적용되는 공통 설정
spring:
  profiles:
    active: prod
  jpa:
    # JPA 관련 공통 설정
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    redis:
      port: 6379

# JWT 관련 공통 설정
jwt:
  secret: ${JWT_SECRET}
  access-token-validity-seconds: 3600    # 1시간
  refresh-token-validity-seconds: 604800 # 7일